apiVersion: v1
kind: PersistentVolume
metadata:
  name: trivy-pv
  labels:
    app: harbor
    component: trivy
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  hostPath:
    path: /mnt/data/trivy
    type: DirectoryOrCreate
