apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    app: harbor
    component: redis
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2-csi
  hostPath:
    path: /mnt/data/redis
