apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: harborlast
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode no
    port 6379
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    daemonize no
    save 900 1
    save 300 10
    save 60 10000
    dbfilename dump.rdb
    dir /data
    requirepass harborRedis2025!
