apiVersion: v1
kind: Service
metadata:
  name: portal
  namespace: harborlast
spec:
  type: LoadBalancer
  ports:
    - port: 80                   # Expose external port 80
      targetPort: 80             # Map to container's port 80
      protocol: TCP
      name: http
  selector:
    app: portal
