apiVersion: v1
kind: Service
metadata:
  name: portal
  namespace: harborlast
spec:
  type: LoadBalancer
  ports:
    - port: 8080                # Expose port 8080 to external users
      targetPort: 8080          # Map to the container's port 8080
      protocol: TCP
      name: http
  selector:
    app: portal
