apiVersion: v1
kind: Service
metadata:
  name: portal
  namespace: harborlast
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: portal
