apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-portal
  namespace: harborlast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-portal
  template:
    metadata:
      labels:
        app: harbor-portal
    spec:
      securityContext:
        fsGroup: 10000
      containers:
        - name: portal
          image: goharbor/harbor-portal:v2.12.2
          ports:
            - containerPort: 8080
              protocol: TCP
          securityContext:
            runAsUser: 10000
            runAsGroup: 10000
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /index.html
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /index.html
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
          volumeMounts:
            - name: portal-data
              mountPath: /usr/share/nginx/html
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: portal-data
          persistentVolumeClaim:
            claimName: portal-pvc
        - name: config
          configMap:
            name: portal-config
            items:
              - key: nginx.conf
                path: nginx.conf
