apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portal-pvc
  namespace: harborlast
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp2
