apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  namespace: harborlast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
        - name: portal
          image: goharbor/harbor-portal:v2.12.2
          ports:
            - containerPort: 80      # Change container port to 80
          volumeMounts:
            - name: portal-data
              mountPath: /usr/share/nginx/html
      volumes:
        - name: portal-data
          persistentVolumeClaim:
            claimName: portal-pvc
