apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portal-pvc
  namespace: harborlast
  labels:
    app: portal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Gi"  # Corrected to string format
  storageClassName: gp2-csi  # Corrected for dynamic provisioning
