apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  namespace: harborlast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      securityContext:
        fsGroup: 10000
      containers:
        - name: portal
          image: goharbor/harbor-portal:v2.12.2
          ports:
            - containerPort: 8080
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: true
          livenessProbe:
            httpGet:
              path: /index.html
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /index.html
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: portal-data
              mountPath: /data/portal
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: config
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: portal-data
          persistentVolumeClaim:
            claimName: portal-pvc
        - name: config
          configMap:
            name: portal-config
