apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-config
  namespace: harborlast
  labels:
    app: portal
data:
  nginx.conf: |
    # Nginx Configuration for Harbor Portal
    worker_processes  1;
    events {
      worker_connections  1024;
    }
    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      server {
        listen 8080;
        server_name localhost;

        location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
        }

        location /api/ {
          proxy_pass http://core:8080/api/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        error_page  404 /404.html;
        location = /404.html {
          root   /usr/share/nginx/html;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
          root   /usr/share/nginx/html;
        }
      }
    }
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Harbor Portal</title>
    </head>
    <body>
      <h1>Welcome to Harbor v2.12.2</h1>
      <p>This is the Harbor Portal UI.</p>
    </body>
    </html>
