apiVersion: v1
kind: PersistentVolume
metadata:
  name: portal-pv
  namespace: harborlast
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2-csi
  hostPath:
    path: /mnt/data/harbor-portal
