apiVersion: v1
kind: PersistentVolume
metadata:
  name: portal-pv
  labels:
    app: portal
spec:
  capacity:
    storage: 10Gi  # Correct size
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2-csi  # Correct storage class
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/portal  # Local path for portal data
    type: DirectoryOrCreate  # Ensures directory is created if missing
