apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portal-pvc
  namespace: harborlast
  labels:
    app: portal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Increase size as needed
  storageClassName: gp2-csi  # Correct for dynamic provisioning
