apiVersion: v1
kind: Service
metadata:
  name: harbor-portal
  namespace: harborlast
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: harbor-portal
