apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  namespace: harborlast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      securityContext:
        fsGroup: 1000  # Ensures proper access to mounted volumes
      containers:
        - name: portal
          image: goharbor/harbor-portal:v2.12.2
          ports:
            - containerPort: 8080
          securityContext:
            runAsUser: 1000  # Non-root for security
            runAsGroup: 1000
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: portal-data
              mountPath: /mnt/data/portal   # Correct mountPath for portal
      volumes:
        - name: portal-data
          persistentVolumeClaim:
            claimName: portal-pvc
