apiVersion: v1
kind: PersistentVolume
metadata:
  name: portal-pv
  namespace: harborlast
  labels:
    app: portal
spec:
  capacity:
    storage: 10Gi  # Set the required size
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2-csi  # Updated to gp2-csi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/portal  # Local path for storing portal data
  

