apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portal-pvc
  namespace: harborlast
spec:
  storageClassName: gp2-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
