apiVersion: v1
kind: PersistentVolume
metadata:
  name: portal-pv
  namespace: harborlast
spec:
  storageClassName: gp2-csi
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/portal
