apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  namespace: harborlast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      securityContext:
        fsGroup: 10000  # Ensures proper access to mounted volumes
      containers:
        - name: portal
          image: goharbor/harbor-portal:v2.12.2
          ports:
            - containerPort: 8080
          securityContext:
            runAsUser: 10000  # Corrected user
            runAsGroup: 10000
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: portal-data
              mountPath: /data/portal  # Corrected mountPath for portal
      volumes:
        - name: portal-data
          persistentVolumeClaim:
            claimName: portal-pvc
