apiVersion: v1
kind: PersistentVolume
metadata:
  name: portal-pv
  namespace: harborlast
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  hostPath:
    path: /mnt/data/portal
