apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobservice
  namespace: harborlast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobservice
  template:
    metadata:
      labels:
        app: jobservice
    spec:
      containers:
      - name: jobservice
        image: goharbor/harbor-jobservice:v2.12.2
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /etc/app.conf
          subPath: app.conf
        - name: config
          mountPath: /etc/jobservice/harbor.yml
          subPath: harbor.yml
        - name: data
          mountPath: /mnt/data/jobservice
      volumes:
      - name: config
        configMap:
          name: harbor-config
      - name: data
        persistentVolumeClaim:
          claimName: jobservice-pvc
