apiVersion: v1
kind: Service
metadata:
  name: jobservice
  namespace: harborlast
  labels:
    app: jobservice
spec:
  type: LoadBalancer
  ports:
    - name: jobservice
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 8081
      targetPort: 8081
  selector:
    app: jobservice
