apiVersion: v1
kind: PersistentVolume
metadata:
  name: jobservice-pv
  labels:
    app: harbor
    component: jobservice
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  hostPath:
    path: /mnt/data/jobservice
