apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.harbor.secret.name }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "certs/harbor.crt" | b64enc | quote }}
  tls.key: {{ .Files.Get "certs/harbor.key" | b64enc | quote }}
