apiVersion: v2
name: custom-harbor
version: 1.0.0
appVersion: 2.12.2
description: A Helm chart to deploy Harbor with custom storage and backend configurations.
type: application

dependencies:
  - name: harbor
    version: 2.12.2
    repository: https://helm.goharbor.io