apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-config
  namespace: harborlast
data:
  app.conf: |
    appname = Harbor
    runmode = prod
    enablegzip = true
    [session]
    session_provider = memory
  config.yml: |
    version: 2.12.2
    log:
      level: info
      fields:
        service: registry
    storage:
      filesystem:
        rootdirectory: /mnt/data/harbor/registry
    auth:
      htpasswd:
        realm: harbor-registry-basic
        path: /etc/registry/passwd
  harbor.yml: |
    hostname: harbor.local
    https:
      enabled: false
    database:
      password: changeMe
    harbor_admin_password: Harbor12345
    data_volume: /mnt/data/harbor
    redis:
      host: harbor-redis
      port: 6379
      password: redispassword
      db_index: 1
    cache:
      enabled: true
      expire_hours: 24
      type: redis
