apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-pv
  namespace: harborlast
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2-csi
  hostPath:
    path: /mnt/data/harbor
