apiVersion: v1
kind: Service
metadata:
  name: harbor
  namespace: harborlast
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: harbor-core
