apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-config
  namespace: harborlast
data:
  app.conf: |
    appname = Harbor
    runmode = prod
    enablegzip = true
    [session]
    session_provider = redis
    session_provider_config = redis://:redispassword@harbor-redis:6379/0

  harbor.yml: |
    hostname: harbor.local
    http:
      port: 80
    https:
      enabled: true           # Enable HTTPS
      port: 443               # Default HTTPS port
      certificate: /etc/harbor/certs/harbor-cert-secret.yaml  # Correct certificate path
      private_key: /etc/harbor/certs/harbor-cert-secret.yaml  # Correct private key path
    internal_tls:
      enabled: false
    database:
      host: harbor-postgresql
      port: 5432
      username: postgres
      password: changeMe
      database: registry
      sslmode: disable
    harbor_admin_password: Harbor12345
    data_volume: /mnt/data/harbor

    # Cache settings
    cache:
      type: "redis"
      redis_url: "redis://:redispassword@harbor-redis:6379/1"
