apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-config
  namespace: harborlast
data:
  app.conf: |
    appname = Harbor
    runmode = prod
    enablegzip = true
    [session]
    session_provider = memory
  harbor.yml: |
    hostname: harbor.local
    https:
      enabled: false
    internal_tls:
      enabled: false
    database:
      password: changeMe
    harbor_admin_password: Harbor12345
    data_volume: /mnt/data/harbor
    redis:
      host: harbor-redis
      port: 6379
      password: redispassword
      db_index: 1
    cache:
      enabled: true
      expire_hours: 24
      type: redis
