apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-config
  namespace: harborlast
data:
  app.conf: |
    appname = Harbor
    runmode = prod
    enablegzip = true
    [session]
    session_provider = memory

  harbor.yml: |
    hostname: harbor.local
    http:
      port: 80
    https:
      enabled: true           # Enable HTTPS
      port: 443               # Default HTTPS port
      certificate: /etc/harbor/certs/harbor.crt  # Path to the SSL certificate
      private_key: /etc/harbor/certs/harbor.key  # Path to the SSL private key
    internal_tls:
      enabled: false
    database:
      host: harbor-postgresql
      port: 5432
      username: postgres
      password: changeMe
      database: registry
      sslmode: disable
    harbor_admin_password: Harbor12345
    data_volume: /mnt/data/harbor

    # Cache settings
    cache:
      enabled: true
      expire_hours: 24
      type: redis
      redis:
        host: harbor-redis
        port: 6379
        password: redispassword
        db_index: 1
