apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor
  namespace: harborlast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor
  template:
    metadata:
      labels:
        app: harbor
    spec:
      containers:
      - name: harbor
        image: goharbor/harbor-core:v2.12.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: harbor-data
          mountPath: /mnt/data/harbor
        - name: harbor-config
          mountPath: /etc/core/app.conf
          subPath: app.conf
        - name: harbor-config
          mountPath: /etc/registry/passwd
          subPath: config.yml
        - name: harbor-config
          mountPath: /etc/harbor/harbor.yml
          subPath: harbor.yml
      volumes:
      - name: harbor-data
        persistentVolumeClaim:
          claimName: harbor-pvc
      - name: harbor-config
        configMap:
          name: harbor-config
