apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-core
  namespace: harborlast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-core
  template:
    metadata:
      labels:
        app: harbor-core
    spec:
      containers:
        - name: harbor-core
          image: goharbor/harbor-core:v2.12.2
          ports:
            - containerPort: 8080  # HTTP port
              protocol: TCP
            - containerPort: 8443  # HTTPS port for internal Harbor communication
              protocol: TCP
          env:
            - name: CORE_SECRET
              valueFrom:
                secretKeyRef:
                  name: harbor-secrets
                  key: CORE_SECRET
            - name: JOBSERVICE_SECRET
              valueFrom:
                secretKeyRef:
                  name: harbor-secrets
                  key: JOBSERVICE_SECRET
          volumeMounts:
            - name: core-config
              mountPath: /etc/harbor/core/app.conf
              subPath: app.conf
            - name: core-config
              mountPath: /etc/harbor/core/config.yml
              subPath: config.yml
            - name: harbor-config
              mountPath: /etc/harbor/harbor.yml
              subPath: harbor.yml
            - name: data
              mountPath: /mnt/data/harbor
            - name: tls-certificates
              mountPath: /etc/harbor/certs
              readOnly: true
      volumes:
        - name: core-config
          configMap:
            name: harbor-core-config
        - name: harbor-config
          configMap:
            name: harbor-config
        - name: data
          persistentVolumeClaim:
            claimName: harbor-pvc
        - name: tls-certificates
          secret:
            secretName: harbor-tls
            optional: true
