apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor
  namespace: harborlast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor
  template:
    metadata:
      labels:
        app: harbor
    spec:
      containers:
      - name: harbor
        image: goharbor/harbor-core:v2.12.2
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /etc/app.conf
          subPath: app.conf
        - name: config
          mountPath: /etc/harbor/harbor.yml
          subPath: harbor.yml
        - name: data
          mountPath: /mnt/data/harbor
        - name: ssl
          mountPath: /etc/harbor/ssl
      volumes:
      - name: config
        configMap:
          name: harbor-config
      - name: data
        persistentVolumeClaim:
          claimName: harbor-pvc
      - name: ssl
        emptyDir: {}
