apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:15.4
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pg-data
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_USER
          value: "harbor"   # Default username for Harbor
        - name: POSTGRES_PASSWORD
          value: "HarborPass123"   # Set a strong password here
        - name: POSTGRES_DB
          value: "registry"   # Database name for Harbor registry
      volumes:
      - name: pg-data
        persistentVolumeClaim:
          claimName: postgresql-pvc
