apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: goharbor/registry-photon:v2.12.2
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: registry-data
          mountPath: /storage
      volumes:
      - name: registry-data
        persistentVolumeClaim:
          claimName: registry-pvc