apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
  labels:
    app: harbor
    component: registry
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2-csi
  hostPath:
    path: /mnt/data/registry
